version: "3.9"
services:
  blog:
    container_name: 'blog'
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    stop_signal: SIGINT
    ports:
      - '4000:4000'
    restart: "unless-stopped"
