# NOTE: These are only default values for the web application.
# It is expected that these values will be overriden using
# environment variables in live environments.
app:
  env: "development"
  url: ":4000"
  user: "admin"
  password: "password"
  realm: "realm"
database:
  dsn: "postgresql://postgres:postgres@database:5432?database=blog"
