name: Build and Publish to DigitalOcean

on: workflow_dispatch

env:
  REGISTRY: registry.digitalocean/r3d5un
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: docker build -t ${{ env.IMAGE_NAME }}:latest .

      - name: Install DigitalOcean CLI Tools
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: DigitalOcean Registry Login
        run: doctl registry login --expiry-seconds 600

      - name: Tag Image
        run:
          docker tag ${{ env.IMAGE_NAME }}:latest \
          registry.digitalocean.com/r3d5un/${{ env.IMAGE_NAME }}:latest

      - name: DigitalOcean Registry Push
        run: docker push registry.digitalocean.com/r3d5un/${{ env.IMAGE_NAME }}:latest
